export const queryKeys = {
    /*Temporary*/
    FETCH_TEMPORARY_LIST: 'FETCH_TEMPORARY_LIST',
    /*Authentication && Authorization*/
    AUTHENTICATION_LOGIN: 'AUTHENTICATION_LOGIN',
    AUTHENTICATION_FETCH_PROFILE: 'AUTHENTICATION_FETCH_PROFILE',
    AUTHENTICATION_TOKEN_VERIFY: 'AUTHENTICATION_TOKEN_VERIFY',
    AUTHENTICATION_REGISTER: 'AUTHENTICATION_REGISTER',
    AUTHORIZATION_GROUPS: 'AUTHORIZATION_GROUPS',
    AUTHORIZATION_GROUPS_CREATE: 'AUTHORIZATION_GROUPS_CREATE',
    AUTHORIZATION_GROUPS_UPDATE: 'AUTHORIZATION_GROUPS_UPDATE',
    AUTHORIZATION_GROUPS_DETAIL: 'AUTHORIZATION_GROUPS_DETAIL',
    AUTHORIZATION_GROUPS_DELETE: 'AUTHORIZATION_GROUPS_DELETE',
    AUTHORIZATION_PERMISSIONS: 'AUTHORIZATION_PERMISSIONS',
    AUTHORIZATION_USERS: 'AUTHORIZATION_USERS',
    AUTHORIZATION_USERS_UPDATE: 'AUTHORIZATION_USERS_UPDATE',
    AUTHORIZATION_USERS_CREATE: 'AUTHORIZATION_USERS_CREATE',
    /*reports*/
    FETCH_REPORTS_AR: 'FETCH_REPORTS_AR',
    FETCH_REPORTS_AR_BY_COUNT: 'FETCH_REPORTS_AR_BY_COUNT',
    FETCH_REPORTS_AR_BY_BALANCE: 'FETCH_REPORTS_AR_BY_BALANCE',
    FETCH_REPORTS_AR_BY_LOCATION: 'FETCH_REPORTS_AR_BY_LOCATION',
    FETCH_REPORTS_AR_BY_PAYER_GROUP: 'FETCH_REPORTS_AR_BY_PAYER_GROUP',
};